name: Deploy Front End App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - front/**
      - .github/workflows/deployFront.yml

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-22.04
    name: Build and Deploy Job
    defaults:
      run:
        working-directory: front
    strategy:
      matrix:
        node-version: [18]
    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: front/pnpm-lock.yaml

    - name: Install dependencies
      run: pnpm install

    - name: Build App
      run: pnpm run build

    - name: Deploy
      id: buildproductiondeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.azure_static_web_app_token }}
        action: "upload"
        app_location: "/front/dist"
        output_location: "dist"                     