name: Deploy API

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - api/**
      - .github/workflows/deployApi.yml

jobs:
  build:

    defaults:
      run:
        working-directory: api

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
        distribution: 'microsoft'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: my-app-path
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v3
      with:
        app-name: my-app-name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: my/target/*.jar